# A dictionary of lists whose base color is used as the key
allColors = [
    "orange", "darkorange", "papayawhip", "peachpuff", "salmon",
    "blue", "darkblue", "lightblue", "mediumblue", "deepskyblue","lightskyblue", "skyblue", "powderblue",
    "green", "darkgreen", "lightgreen", "lawngreen", "yellowgreen", "limegreen", "mediumspringgreen", "springgreen", "lightseagreen", "seagreen", "mediumseagreen", "darkseagreen",
    "yellow", "lightyellow", "greenyellow", "lightgoldenrodyellow",
    "gray", "darkgray", "lightgray", "slategray", "darkslategray", "lightslategray",
    "purple", "mediumpurple", "rebeccapurple", "plum",
    "turquoise", "darkturquoise", "paleturquoise", "mediumturquoise",
    "violet", "darkviolet", "blueviolet", "mediumvioletred", "palevioletred",
    "brown", "rosybrown", "saddlebrown", "sandybrown",
    "red", "darkred", "indianred", "orangered",
];

# All of the other color options that can be used in go.Scatter(line=dict(color=***))

# "aliceblue", "antiquewhite", "aqua", "aquamarine", "azure",
# "beige", "bisque", "black", "blanchedalmond", 
# "burlywood", "cadetblue",
# "chartreuse", "chocolate", "coral", "cornflowerblue",
# "cornsilk", "crimson", "cyan", "darkcyan",
# "darkgoldenrod", "darkgrey",
# "darkkhaki", "darkmagenta", "darkolivegreen", 
# "darkorchid", "darksalmon",
# "darkslateblue", "darkslategrey",
# "deeppink",
# "dimgray", "dimgrey", "dodgerblue", "firebrick",
# "floralwhite", "forestgreen", "fuchsia", "gainsboro",
# "ghostwhite", "gold", "goldenrod", "grey",     "honeydew", "hotpink", "indigo",
# "ivory", "khaki", "lavender", "lavenderblush",
# "lemonchiffon", "lightcoral", "lightcyan",
# "lightgrey",
# "lightpink", "lightsalmon",
# "lightslategrey",
# "lightsteelblue", "lime",
# "linen", "magenta", "maroon", "mediumaquamarine",
# "mediumorchid",
# "mediumslateblue",
# "midnightblue",
# "mintcream", "mistyrose", "moccasin", "navajowhite", "navy",
# "oldlace", "olive", "olivedrab", "orchid", "palegoldenrod", "palegreen", 
# "pink",
# "royalblue",
# "seashell", "sienna", "silver",
# "slateblue", "slategrey", "snow",
# "steelblue", "tan", "teal", "thistle", "tomato",
# "wheat", "white", "whitesmoke",

